# This actions is created referring https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# Tag is required for it is able to be used.

name: 'Add Registry'
description: 'Add Registry to Julia Environment'
inputs:
  author-name:  # id of input
    description: 'author/repo for your registry hosted under Github'
    required: false
    default: 'okatsn/OkRegistry'

runs:
  using: "composite"
  steps:
    - run: |
        julia --project=@. -e '
          using Pkg;
          Pkg.instantiate() # This will download General Registry if it is not installed.
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/${{ inputs.author-name }}.git"));
          Pkg.Registry.update();
          '
      shell: bash
